apiVersion: v1
kind: Secret
metadata:
  name: skillpulse-db
  namespace: skillpulse
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: rootpassword123
  MYSQL_DATABASE: skillpulse
  MYSQL_USER: skillpulse
  MYSQL_PASSWORD: skillpulse123